services:
  postgres:
    image: postgres:18
    container_name: industrial-maintenance-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: