CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_users PRIMARY KEY (id),

    CONSTRAINT ck_users_full_name_length
        CHECK (CHAR_LENGTH(BTRIM(full_name)) BETWEEN 2 AND 100),

    CONSTRAINT ck_users_full_name_trimmed
        CHECK (full_name = BTRIM(full_name)),

    CONSTRAINT ck_users_email_not_blank
        CHECK (CHAR_LENGTH(email) > 0),

    CONSTRAINT ck_users_email_normalized
        CHECK (email = LOWER(BTRIM(email))),

    CONSTRAINT ck_users_password_hash_not_blank
        CHECK (CHAR_LENGTH(password_hash) > 0),

    CONSTRAINT ck_users_role
        CHECK (role IN ('ADMIN', 'TECHNICIAN', 'REQUESTER'))
);

CREATE UNIQUE INDEX ux_users_email_lower
    ON users (LOWER(email));