CREATE TABLE equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    inventory_number VARCHAR(50) NOT NULL,
    description VARCHAR(1000),
    location VARCHAR(120) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPERATIONAL',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_equipment PRIMARY KEY (id),

    CONSTRAINT ck_equipment_name_length
        CHECK (CHAR_LENGTH(BTRIM(name)) BETWEEN 2 AND 120),

    CONSTRAINT ck_equipment_name_trimmed
        CHECK (name = BTRIM(name)),

    CONSTRAINT ck_equipment_inventory_number_length
        CHECK (
            CHAR_LENGTH(BTRIM(inventory_number))
            BETWEEN 2 AND 50
        ),

    CONSTRAINT ck_equipment_inventory_number_trimmed
        CHECK (inventory_number = BTRIM(inventory_number)),

    CONSTRAINT ck_equipment_description
        CHECK (
            description IS NULL
            OR (
                CHAR_LENGTH(description) BETWEEN 1 AND 1000
                AND description = BTRIM(description)
            )
        ),

    CONSTRAINT ck_equipment_location_length
        CHECK (CHAR_LENGTH(BTRIM(location)) BETWEEN 2 AND 120),

    CONSTRAINT ck_equipment_location_trimmed
        CHECK (location = BTRIM(location)),

    CONSTRAINT ck_equipment_status
        CHECK (
            status IN (
                'OPERATIONAL',
                'UNDER_REPAIR',
                'OUT_OF_SERVICE',
                'DECOMMISSIONED'
            )
        )
);

CREATE UNIQUE INDEX ux_equipment_inventory_number_lower
    ON equipment (LOWER(inventory_number));

CREATE INDEX ix_equipment_status
    ON equipment (status);