CREATE TABLE maintenance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    equipment_id BIGINT NOT NULL,
    repair_request_id BIGINT NOT NULL,
    performed_by_id BIGINT NOT NULL,
    work_description TEXT NOT NULL,
    performed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_maintenance_records PRIMARY KEY (id),
    CONSTRAINT uq_maintenance_records_repair_request UNIQUE (repair_request_id),
    CONSTRAINT fk_maintenance_records_equipment
        FOREIGN KEY (equipment_id) REFERENCES equipment (id),
    CONSTRAINT fk_maintenance_records_repair_request
        FOREIGN KEY (repair_request_id) REFERENCES repair_requests (id),
    CONSTRAINT fk_maintenance_records_performed_by
        FOREIGN KEY (performed_by_id) REFERENCES users (id),
    CONSTRAINT ck_maintenance_records_work_description
        CHECK (CHAR_LENGTH(BTRIM(work_description)) > 0
            AND work_description = BTRIM(work_description))
);

CREATE INDEX ix_maintenance_records_equipment_performed_at
    ON maintenance_records (equipment_id, performed_at DESC, id DESC);
